language: go
go: 1.1
before_install:
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr mercurial git libyaml-dev -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)
install:
  - curl -sL https://github.com/kr/beanstalkd/archive/v1.9.tar.gz | tar -xzC /tmp -
  - pushd /tmp/beanstalkd-1.9
  - make -j4 > make.out 2>&1 || (cat make.out && exit 1)
  - ./beanstalkd -l 127.0.0.1 -p 11300 &
  - sleep 1
  - nc -z 127.0.0.1 11300
  - popd
  - make get-test
before_script:
  - ./check-fmt.sh
  - make get-prod
script:
  - make test
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
  email:
    recipients:
      - tsuru@corp.globo.com
    on_success: change
    on_failure: always
services:
  - mongodb
  - redis
