language: go
go:
  - 1.4
  - tip
env:
  - GOARCH=amd64
matrix:
  allow_failures:
    - go: tip
before_install:
  - sed -i "s|git://github.com/tsuru/tsuru.git|https://github.com/tsuru/tsuru|g" .git/config
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr mercurial git -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - echo http://localhost > $HOME/.tsuru_target
  - make get GO_EXTRAFLAGS=-x
before_script:
  - nc -zvv localhost 27017; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 27017..."; nc -zvv localhost 27017; out=$?; sleep 1; done
  - nc -zvv localhost 6379; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 6379..."; nc -zvv localhost 6379; out=$?; sleep 1; done
script:
  - make test GO_EXTRAFLAGS=-x
notifications:
  email:
    recipients:
      - tsuru@corp.globo.com
    on_success: change
    on_failure: always
services:
  - mongodb
  - redis
