language: go
go:
  - 1.4
  - tip
env:
  - GOARCH=amd64
matrix:
  allow_failures:
    - go: tip
before_install:
  - sed -i "s|git://github.com/tsuru/tsuru.git|https://github.com/tsuru/tsuru|g" .git/config
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr mercurial git -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/mysql stop
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - echo http://localhost > $HOME/.tsuru_target
  - make get GO_EXTRAFLAGS=-x
before_script:
  # Check baseline memory usage; for compare with after_failure when OOM occurs
  - free
  - vmstat
  - ps aux --sort -rss | head -n 10
  - mongostat -n 1
  # Make sure MongoDB and Redis are available
  - nc -zvv localhost 27017; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 27017..."; nc -zvv localhost 27017; out=$?; sleep 1; done
  - nc -zvv localhost 6379; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 6379..."; nc -zvv localhost 6379; out=$?; sleep 1; done
script:
  - travis_retry make test GO_EXTRAFLAGS=-x GOMAXPROCS=1
after_failure:
  # check for OOM; see https://github.com/travis-ci/travis-ci/issues/3075#issuecomment-68629130
  - sudo dmesg
  - free
  - vmstat
  - ps aux --sort -rss | head -n 10
  # mongostat might not work though if mongod was the process that was OOM-killed
  - mongostat -n 1
after_success:
  # So we can see how much memory is used on success, it is probably borderline
  # Here we can get useful output from mongostat since mongod wasn't OOM-killed
  - free
  - vmstat
  - ps aux --sort -rss | head -n 10
  - mongostat -n 1
notifications:
  email:
    recipients:
      - tsuru@corp.globo.com
    on_success: change
    on_failure: always
services:
  - mongodb
  - redis
