language: go
go:
  - 1.1.2
  - 1.2
  - tip
env:
  - GOARCH=amd64
  - GOARCH=386
before_install:
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr mercurial git -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)
  - sudo git clone https://git.fedorahosted.org/git/lvm2.git /usr/local/lvm2
  - pushd /usr/local/lvm2
  - sudo git checkout v2_02_103
  - sudo ./configure --enable-static_link
  - sudo make device-mapper
  - sudo make install_device-mapper
  - popd
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - curl -sL https://github.com/kr/beanstalkd/archive/v1.9.tar.gz | tar -xzC /tmp
  - pushd /tmp/beanstalkd-1.9
  - make -j4 > make.out 2>&1 || (cat make.out && exit 1)
  - ./beanstalkd -l 127.0.0.1 -p 11300 &
  - sleep 1
  - nc -z 127.0.0.1 11300
  - popd
  - make get-test
before_script:
  - git clean -dfX
  - make get-prod godep
  - rm -rf src
  - echo http://localhost > $HOME/.tsuru_target
script:
  - export PATH="$HOME/gopath/bin:$PATH"
  - make test
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
  email:
    recipients:
      - tsuru@corp.globo.com
    on_success: change
    on_failure: always
services:
  - mongodb
  - redis
