language: go
sudo: false
go:
  - 1.4.2
  - 1.5.2
  - tip
env:
  - GOARCH=amd64
addons:
  apt:
    packages:
      - rsyslog
install:
  - make get
before_script:
  - rsyslogd &
  - sleep 1
script:
  - make test
  - ./check-fmt.sh
  - make deadcode
  - ./check-handlers.sh
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: QJe4k18ACRUP4CDo245vBFu1hpVlcR3JPWjT7NL/vAE/Y5KDn5pNXIREPYIx9F/f8lvjF2RrQxjApeUujRh1PPt2Q53JulvaDCfM5a5SYnk5yoqu3ynlfqU4AOTDa6kzoJ3K4M9X8JhMpOtr3+IOPbwV88FjPvwviZN4p0L/0wc=
services:
  - mongodb
  - redis
matrix:
  allow_failures:
    - go: tip
