language: go
go:
  - 1.1.2
  - 1.2
  - tip
env:
  - GOARCH=amd64
before_install:
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr mercurial git -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)
  - sudo add-apt-repository ppa:tsuru/lvm2 -y
  - sudo apt-get update
  - sudo apt-get install -q libdevmapper-dev
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - curl -sL https://github.com/kr/beanstalkd/archive/v1.9.tar.gz | tar -xzC /tmp
  - pushd /tmp/beanstalkd-1.9
  - make -j4 > make.out 2>&1 || (cat make.out && exit 1)
  - ./beanstalkd -l 127.0.0.1 -p 11300 &
  - sleep 1
  - nc -z 127.0.0.1 11300
  - popd
  - go get github.com/dotcloud/tar
  - make get
script:
  - make test
notifications:
  email:
    recipients:
      - tsuru@corp.globo.com
    on_success: change
    on_failure: always
services:
  - mongodb
  - redis
