language: go
sudo: required
install: true
go:
  - 1.6.4
  - 1.7.4
  - tip
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.7.3
    - IMAGE_NAME=tsuru/api
addons:
  apt:
    packages:
      - rsyslog
      - xmlsec1
before_script:
  - rsyslogd &
  - sleep 1
before_install:
  - sleep 15
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
  - sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
  - sudo ifconfig
  - sudo sysctl -a | grep ipv6.conf
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  - sudo apt-get -qq update
  - sudo apt-get install -y mongodb-org
  - sudo service mongod start || true
  - service mongod status
  - go env && pwd
script:
  - make test
  - while true; do echo .; sleep 30; done &
  - if [ "${TRAVIS_EVENT_TYPE}" = "push" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then make lint; else make metalint; fi
  - go get golang.org/x/net/http2/...
  - ./misc/check-handlers.sh
  - ./misc/check-events.sh
  - make check-api-doc
  - CGO_ENABLED=0 go build ./cmd/tsurud/
after_success:
  - curl https://raw.githubusercontent.com/tsuru/push-to-docker/master/push.sh | bash
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: QJe4k18ACRUP4CDo245vBFu1hpVlcR3JPWjT7NL/vAE/Y5KDn5pNXIREPYIx9F/f8lvjF2RrQxjApeUujRh1PPt2Q53JulvaDCfM5a5SYnk5yoqu3ynlfqU4AOTDa6kzoJ3K4M9X8JhMpOtr3+IOPbwV88FjPvwviZN4p0L/0wc=
services:
  - redis
  - docker
  - mongodb
matrix:
  allow_failures:
    - go: tip
